version: 2
updates:

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 5 * * *"
    open-pull-requests-limit: 10
    assignees:
      - jajik

