# Looks like unnecessary, but this is used in the list of defined workflows, so if unspecified,
# the name of the whole workflow (not an individual run) would be `.github/workflows/manual.yml`
name: Manual
# We'll use `Manual` if inputs.note is not defined, otherwise, we'll add the note into parentheses
run-name: ${{ inputs.note && format('Manual ({0})', inputs.note) || format('Manual') }}

on:
  workflow_dispatch:
    inputs:

      note:
        description: "Note to be displayed alongside the workflow run name"
        type: string

      additional-sources:
        description: "A list of URLs, separated by commas, to obtain zip distributions of additional mod_proxy_cluster sources"
        type: string

      tomcat-count:
        description: "Number of tomcat used in tests"
        type: number
        default: 2

      action:
        description: "Action that will happen randomly to running tomcats"
        default: "disable"
        type: choice
        options:
          - "shutdown"
          - "disable"

      action-count:
        description: "Number of tomcats affected by the action chosen"
        type: number
        default: 1      

      clients:
        description: "Number of clients (connections)"
        type: number
        default: 100

      requests:
        description: "Number of requests per client"
        type: number
        default: 1000

      repetitions:
        description: "Number of runs executed for each mod_proxy_cluster distribution"
        type: number
        default: 10

      log-level:
        description: "httpd's log level"
        type: choice
        default: "warn"
        # use just a subset
        options: [ "error", "notice", "info", "debug", "trace3", "trace8" ]

jobs:

  manual-run:
    runs-on: ubuntu-latest
    env:
      HTTPD_LOG_LEVEL: ${{ inputs.log-level }}
      TOMCAT_COUNT: ${{ inputs.tomcat-count }}
      CONC_COUNT: ${{ inputs.clients }}
      REQ_COUNT: ${{ inputs.requests }}
      REPETITIONS: ${{ inputs.repetitions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Get dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install moby-engine moby-cli gcc maven git curl iproute2 wcstools g++ cmake liblist-moreutils-perl unzip wget

      - name: Get additional mod_proxy_cluster sources
        if: ${{ inputs.additional-sources }}
        run: |
            for source in $(echo ${{ inputs.additional-sources }} | sed 's|,|\n|g'); do
                wget $source && unzip $(filename $source)
                # rename the source if necessary (e.g. in case of the old repository)
                file=$(filename $source)
                version=${file%.*}
                # if the correct directory exists already, we don't rename
                if [ ! -d mod_proxy_cluster-$version/ ]; then
                    mv *-$version/ mod_proxy_cluster-$version/
                fi
            done

      - name: Setup  performance tests
        run: sh setup.sh

      - name: Run performance tests
        run: |
            # first we need to determine the action chosen
            if [ ${{ inputs.action }} == "shutdown" ]; then
                SHUTDOWN_RANDOMLY=${{ inputs.action-count }} sh run-suite.sh 
            else
                DISABLE_RANDOMLY=${{ inputs.action-count }} sh run-suite.sh
            fi

      - name: Make a summary of test runs
        run: perl summary.pl output/ | tee summary && cp summary output/summary-for-${{ matrix.name }}

      - name: Preserve output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output
          path: output/*

